### ISSUE TITLE
Resolve Compatibility Issues with Environment Configuration and LangChain Integration

### ISSUE THREAD

**Issue by DIEAbdulHadi** [MohammedNayeem9/react-fastApi-RAG#1]
### Context  
The current setup has two primary concerns that need addressing:  
1. **Environment Configuration**:  
   - The `.env` variables are not clearly documented, leading to misconfigurations during local setup.  
   - It's essential to ensure seamless onboarding for contributors by providing guidance and validation checks.  

2. **LangChain Integration**:  
   - Deprecation warnings (e.g., `Qdrant` to `QdrantVectorStore`) indicate potential future breakages.  
   - Updating imports and methods to align with the latest LangChain standards is necessary for stability.

---

### Proposed Fix  
1. Enhance documentation to include a sample `.env` file with placeholders for required keys (`QDRANT_API_KEY`, `OPENAI_API_KEY`, etc.).  
2. Refactor LangChain-related code (`rag.py` and `qdrant.py`) to use the recommended `QdrantVectorStore` class and methods from the latest LangChain version.  

---

### Impact  
- Resolves setup confusion for new contributors.  
- Future-proofs the project against LangChain updates.  

---

### Labels  
`bug`, `documentation`, `compatibility`

**Comment by MohammedNayeem9** [comment]
I thought  only LangChain Integration version is the issue here for deprecated stuff 
yes you can contribute and raise the PR let me check out
